	SUBROUTINE BBF(MHZM,JBINSW,IRAYSW,HFREEZE,P_BB,AV_HZMAX,
     +	IRANGE,IAZC)
	DIMENSION MHZM(IRAYSW,JBINSW)

        INCLUDE 'voswin.par'

C ****** COMPUTE THE AVERAGE HEIGHT OF THE MAXIMUM REFLECTIVITY, CONDITIONAL
C ****** ON REFLECTIVITY ANYWHERE IN A COLUMN.
	  IH0=HFREEZE*10	! FREEZING LEVEL
	  NSUM=0		! SUM OF REFLECTIVITY POINTS
	  NSUM0=0		! SUM OF POINTS WHERE HZMAX IS NEAR hfreeze
	  MHZMAXSUM=0		! SUM OF MHZMAX
	  DO IRAY=1,IRAYSW
	    IAZ=IAZC+IRAY-IRAYSW/2
	    IF(IAZ.LT.1)IAZ=IAZ+360
	    DO IBIN=1,JBINSW
	      IR=IRANGE+IBIN-JBINSW/2
	      MMAX = -99
	      IZHFP1=999
	      IZHFM1=999
	      ISHF=IHFSTEP(IR)
	      IZHF=Z(IR,IAZ,ISHF)	! Z nearest to freezing level
	      IF(ISHF.GT.1)IZHFM1=Z(IR,IAZ,ISHF-1)
	      IF(ISHF.LT.NSTEPS)IZHFP1=Z(IR,IAZ,ISHF+1)
	      MVM=MHZM(IRAY,IBIN)
	      IF(MVM.GT.0)THEN
	        NSUM=NSUM+1
	        MHZMAXSUM=MHZMAXSUM+MVM
	        IF(MVM.GE.IH0-15.AND.MVM.LE.IH0+15.OR.
     +		IZHF.GT.IZHFP1.AND.IZHF.GT.IZHFM1)NSUM0=NSUM0+1
		ENDIF
	    END DO
	  END DO

C ****** Calculate average height of HZMAX:

	AV_HZMAX=0
	IF(NSUM.GT.0)AV_HZMAX=0.1*MHZMAXSUM/FLOAT(NSUM)

C ****** Calculate fraction of echo area with HZMAX at freezing level +- 1.5 km.

	P_BB=0
	IF(NSUM.GT.0)P_BB=FLOAT(NSUM0)/FLOAT(NSUM)

	RETURN
	END
